# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gz/msgs/pose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gz.msgs import vector3d_pb2 as gz_dot_msgs_dot_vector3d__pb2
from gz.msgs import quaternion_pb2 as gz_dot_msgs_dot_quaternion__pb2
from gz.msgs import header_pb2 as gz_dot_msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gz/msgs/pose.proto\x12\x07gz.msgs\x1a\x16gz/msgs/vector3d.proto\x1a\x18gz/msgs/quaternion.proto\x1a\x14gz/msgs/header.proto\"\x90\x01\n\x04Pose\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.gz.msgs.Header\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\r\x12#\n\x08position\x18\x04 \x01(\x0b\x32\x11.gz.msgs.Vector3d\x12(\n\x0borientation\x18\x05 \x01(\x0b\x32\x13.gz.msgs.QuaternionB\x19\n\x0b\x63om.gz.msgsB\nPoseProtosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gz.msgs.pose_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013com.gz.msgsB\nPoseProtos'
  _POSE._serialized_start=104
  _POSE._serialized_end=248
# @@protoc_insertion_point(module_scope)
